name: Build & Run kokoro-epub

on:
  workflow_dispatch:
    inputs:
      book:
        description: "Path to EPUB inside app/input/"
        required: true
        default: "input/meta.epub"
      bitrate:
        description: "MP3 bitrate (e.g., 64k, 96k, 128k)"
        required: true
        default: "96k"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Optional: if your EPUB is NOT committed, uncomment and provide a URL
      # - name: Download sample EPUB
      #   run: |
      #     mkdir -p app/input
      #     wget -O app/input/meta.epub "https://example.com/path/to/meta.epub"

      - name: Make output folder
        run: mkdir -p app/output

      - name: Build Docker image
        run: docker build -t kokoro-epub .

      - name: Run conversion (EPUB -> WAVs -> MP3)
        env:
          BOOK_PATH: ${{ github.event.inputs.book }}
          BITRATE: ${{ github.event.inputs.bitrate }}
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE/app/input:/app/input" \
            -v "$GITHUB_WORKSPACE/app/output:/app/output" \
            kokoro-epub \
            python app/cli.py epub "$BOOK_PATH" --out /app/output --merge --bitrate "$BITRATE"

      - name: Upload audiobook artifact (WAVs + MP3)
        uses: actions/upload-artifact@v4
        with:
          name: audiobook
          path: app/output/**
          if-no-files-found: error
